### ISSUE TITLE
Move setting day of completion for single country to Europe class

### ISSUE THREAD

**Issue by akorunska** [KvitkaOlexandr/Euro_Diffusion#1]
https://github.com/KvitkaOlexandr/Euro_Diffusion/blob/ca1d9e36225a0006257340bf92437c4489b50557/Euro_diffusion/Simulator.cs#L51

Day is set manually from the Simulator class. It would be better to make setter method in the Europe class, something like SetSingleCountryCompletionDay.

**Comment by OleksandrKvitka** [comment]
All Country fields are public, it's expedient in this case. But I agree it would be better to assign CompletionDay with a day counter, not just 0.

**Comment by akorunska** [comment]
Yes, I see your point. 
Fine, assigning counter will make enough sense in this situation.
